version: "3.9"

services:

  db:
    image: postgres:16
    container_name: employee-db
    restart: always

    environment:
      POSTGRES_DB: employee_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: 984445750388.dkr.ecr.ap-south-1.amazonaws.com/employee-portal-backend:latest

    container_name: employee-backend

    restart: always

    env_file:
      - .env

    ports:
      - "5000:5000"

    depends_on:
      - db

  frontend:
    image: 984445750388.dkr.ecr.ap-south-1.amazonaws.com/employee-portal-frontend:latest

    container_name: employee-frontend

    restart: always

    ports:
      - "80:80"

    depends_on:
      - backend

volumes:
  postgres_data: